services:
  unicorn-td:
    build: .
    image: unicorn-td:latest
    container_name: unicorn-td
    ports:
      - "3000:3000"
    volumes:
      - unicorn-levels:/app/public/assets/levels
    restart: unless-stopped

volumes:
  unicorn-levels:
