services:
  unicorn-td:
    build: .
    image: unicorn-td:latest
    container_name: unicorn-td
    network_mode: bridge
    ports:
      - "3005:3005"
    volumes:
      - unicorn-levels:/app/public/assets/levels
    restart: unless-stopped

volumes:
  unicorn-levels:
